name: Test and build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: npm install, build, and test
      run: |
        npm ci
        npm test
        npm run production
      env:
        CI: true
